name: aipay
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # Another Snackbar
  another_flushbar: ^1.12.29
  # BLoC
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  # caraousel slider
  carousel_slider: ^4.2.1
  # Generate folder bloc
  equatable: ^2.0.5
  # Qr Code 
  flutter_barcode_scanner: ^2.0.0
  # Flutter State management
  flutter_bloc: ^8.1.2
   # Auto Login
  flutter_secure_storage: ^8.0.0
  # Flutter SVG
  flutter_svg: ^1.1.6
  # google font
  google_fonts: ^3.0.1
  # Http
  http: ^0.13.5
  # image picker
  image_picker: ^0.8.6+1
  # intl
  intl: ^0.17.0
    # Loading animation widget
  loading_animation_widget: ^1.2.0+2
  # Lottie Animation
  lottie: ^2.2.0
  # Url
  url_launcher: ^6.1.7
  # Rive
  rive: ^0.10.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/illustration/
    - assets/images/
    - assets/lottie/
    - assets/rive/


